# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dMMbhdjZkkz4cJD4v7vtqzPTemWVRYh-
"""

print ("hi")
print (7)
print("congratulations")

print(8,"sadaf",True)

print(5*2)

print("welcome to coding.",
"The world of programming is beautiful.")



print("Welcome to coding.\nThe world of programming is beautiful.")
#\n to change the line using one print command.
#It's an escape sequence character( new line character to be more specific).

#Let's just try writing something without without any command.
#we got an error. Syntax highlighting.

print("sadaf is a "girl"")
#use back slash double quotes thats a double quote escape sequence



print("sadaf is a \"girl\"")

7

print('sadaf is a "girl"')

print('sadaf', 'is', 'a', 'girl',7, sep="/" ,end='009\n')
print(4)
#we can use any seperator



