# -*- coding: utf-8 -*-
"""Day48

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_oQBgeOTpWZsfwmpKXT06owRVXjtKkU3
"""

x = 4
print(x)
def hello():
  x =5
  print(f'The local x is{x}')
  print("Hello World")
hello()
print(f'The global x is {x}')

x=7
def hhh():
  global x
  x = 4
  print(x)
hhh()
print(000)
print(999)
print(x)