# -*- coding: utf-8 -*-
"""For Loops

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LkKOr4DFdVyuSVlSogaEPklU_N4HnvIZ
"""

#to execute a program a certain number of times
# two types of loops
#For loop
#while loop
#for loop can iterate over a sequence of iterable objects in python.
Name = 'Sadaf'
for i in Name:
  print(i)
  if(i=="S"):
   print("This is something Special")

Animals=['Horse','Dog','cat', 'squarrel']
for i in Animals:
  print(i)
  for i in i:
    print(i)

#Range
for i in range(5):
 print(i+1)
for k in range(1,7): #start, stop, step
 print(k)
for s in range(0,21,2):
  print(s)